title: Back End and PL
date: 21-10-2020
sessions:
  - title:  
    description:  
    time: "time: NA"
    speaker:
      name:  
      role:  
      about:  
      avatar:  
  - title:  
    description:  
    time: "time: NA"
    speaker:
      name:  
      role:  
      about:  
      avatar:  
  - title:  
    description:  
    time: "time: NA"
    speaker:
      name:  
      role:  
      about:  
      avatar:  
  - title:  
    description:  
    time: "time: NA"
    speaker:
      name:  
      role:  
      about:  
      avatar:  